---
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
  become: true

- name: Start and enable Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: "Copy custom nginx configuration"
  ansible.builtin.template:
    src: "nginx.conf.j2" #"/home/vagrant/ansible/config/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - "Reload nginx"