---
# This role installs Ruby and the necessary dependencies to run the xpaste application

- include_tasks: "install_nodejs.yml"
- include_tasks: "install_ruby_from_source.yml"

- name: Create a .ssh directory
  ansible.builtin.file:
    path: "~/.ssh/"
    state: directory

- name: "Copy private key"
  ansible.builtin.copy:
    src: "~/.ssh/id_rsa"
    dest: "~/.ssh/id_rsa"
    mode: "0600"

- name: "Clone application from remote repository"
  ansible.builtin.git:
    repo: "git@gitlab.slurm.io:edu/xpaste_practicum.git"
    dest: "{{ application_path }}"
    key_file: "~/.ssh/id_rsa"
    accept_hostkey: true

- name: "Configure Bundler"
  ansible.builtin.command: "bundle config build.nokogiri --use-system-libraries"
  args:
    chdir: "{{ application_path }}"

- name: "Install application dependencies"
  ansible.builtin.command: "bundle install --clean --force --no-cache --without development"
  args:
    chdir: "{{ application_path }}"

- name: "Create systemd service file"
  ansible.builtin.template:
    src: "xpaste.service.j2"
    dest: "/etc/systemd/system/xpaste.service"
  notify:
    - "Reload systemd"
    - "Enable and start xpaste"




