# This playbook installs and configures the xpaste application.
# It defines variables for the database user and database name.
# These variables can be overridden if necessary.
# Sensitive information such as password and secret key base is stored encrypted in a secrets.yml file.

# Note: Ensure the 'geerlingguy.nginx' role is installed from Ansible Galaxy before running this playbook.
# You can install the role using the following command:
# ansible-galaxy role install geerlingguy.nginx

---
- name: "Installing xpaste application"
  hosts: "application-servers"
  become: true
  vars_files:
    - secrets.yml
    - main.yml

  roles:
  - postgresql
  - ruby-app-role
  - geerlingguy.nginx
  - nginx_conf_change
