---
- name: "Copy custom nginx configuration"
  ansible.builtin.template:
    src: "nginx.conf.j2" #"{{ application_path }}config/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - "Reload nginx"

